"""Append 6 admin handler functions to SupabaseLayer.js."""
import sys

NEW_CODE = (
    "\n\n"
    "// ══════════════════════════════════════════════════════════════════\n"
    "// ADMIN HANDLER FUNCTIONS  (Supabase-native; require ADMIN_TOKEN)\n"
    "// All 6 functions bypass IS_SUPABASE_ENABLED — they always use\n"
    "// SupabaseService directly.  Authentication: validateAdmin(body.token).\n"
    "// ══════════════════════════════════════════════════════════════════\n"
    "\n"
    "// ─── handleAdminGetSlotsV2 ───────────────────────────────────────\n"
    "// Returns all slots (any status) for a Jerusalem-local date range.\n"
    "// Input: { token, dateFrom:'YYYY-MM-DD', dateTo:'YYYY-MM-DD' }\n"
    "function handleAdminGetSlotsV2(body) {\n"
    "  if (!validateAdmin(body.token)) return { success: false, error: 'unauthorized' };\n"
    "\n"
    "  var dateFrom = String(body.dateFrom || '').trim();\n"
    "  var dateTo   = String(body.dateTo   || '').trim();\n"
    "  if (!dateFrom || !dateTo) return { success: false, error: 'missing_params' };\n"
    "\n"
    "  var fromUtc = _sb_localToUtcIso(dateFrom, '00:00');\n"
    "  var toUtc   = _sb_localToUtcIso(dateTo,   '23:59');\n"
    "\n"
    "  var rows = SupabaseService.select('slots',\n"
    "    'start_time=gte.' + fromUtc +\n"
    "    '&start_time=lte.' + toUtc +\n"
    "    '&order=start_time.asc' +\n"
    "    '&select=id,start_time,end_time,status');\n"
    "\n"
    "  if (!rows) return { success: false, error: 'supabase_unavailable' };\n"
    "\n"
    "  var TZ = 'Asia/Jerusalem';\n"
    "  var slots = rows.map(function (row) {\n"
    "    var dt = new Date(row.start_time);\n"
    "    return {\n"
    "      id:     row.id,\n"
    "      date:   Utilities.formatDate(dt, TZ, 'yyyy-MM-dd'),\n"
    "      time:   Utilities.formatDate(dt, TZ, 'HH:mm'),\n"
    "      status: row.status,\n"
    "    };\n"
    "  });\n"
    "\n"
    "  return { success: true, slots: slots };\n"
    "}\n"
    "\n"
    "// ─── handleAdminAddSlotV2 ────────────────────────────────────────\n"
    "// Adds a single available slot.  Idempotent: ON CONFLICT(start_time).\n"
    "// Input: { token, date:'YYYY-MM-DD', time:'HH:MM' }\n"
    "function handleAdminAddSlotV2(body) {\n"
    "  if (!validateAdmin(body.token)) return { success: false, error: 'unauthorized' };\n"
    "\n"
    "  var date = String(body.date || '').trim();\n"
    "  var time = String(body.time || '').trim();\n"
    "\n"
    "  if (!/^\\d{4}-\\d{2}-\\d{2}$/.test(date) || !/^\\d{2}:\\d{2}$/.test(time)) {\n"
    "    return { success: false, error: 'invalid_params' };\n"
    "  }\n"
    "\n"
    "  var startUtc = _sb_localToUtcIso(date, time);\n"
    "  var endUtc   = new Date(new Date(startUtc).getTime() + 120 * 60 * 1000).toISOString();\n"
    "\n"
    "  var inserted = SupabaseService.insert('slots', {\n"
    "    start_time:   startUtc,\n"
    "    end_time:     endUtc,\n"
    "    status:       'available',\n"
    "    last_updated: new Date().toISOString(),\n"
    "  }, 'start_time');\n"
    "\n"
    "  if (!inserted || !inserted[0]) return { success: false, error: 'insert_failed' };\n"
    "\n"
    "  return {\n"
    "    success: true,\n"
    "    slot: { id: inserted[0].id, date: date, time: time, status: 'available' },\n"
    "  };\n"
    "}\n"
    "\n"
    "// ─── handleAdminDeleteSlotV2 ─────────────────────────────────────\n"
    "// Deletes a slot by id.  Refuses if status is 'booked' or 'pending'.\n"
    "// Input: { token, slotId }\n"
    "function handleAdminDeleteSlotV2(body) {\n"
    "  if (!validateAdmin(body.token)) return { success: false, error: 'unauthorized' };\n"
    "\n"
    "  var id = parseInt(body.slotId, 10);\n"
    "  if (!id) return { success: false, error: 'missing_params' };\n"
    "\n"
    "  var rows = SupabaseService.select('slots', 'id=eq.' + id + '&select=id,status');\n"
    "  if (!rows || !rows.length) return { success: false, error: 'slot_not_found' };\n"
    "  var slot = rows[0];\n"
    "\n"
    "  if (slot.status === 'booked' || slot.status === 'pending') {\n"
    "    return { success: false, error: 'cannot_delete_active', status: slot.status };\n"
    "  }\n"
    "\n"
    "  var result = SupabaseService.delete('slots', 'id=eq.' + id);\n"
    "  if (result === null) return { success: false, error: 'delete_blocked_by_fk' };\n"
    "\n"
    "  return { success: true, slotId: id };\n"
    "}\n"
    "\n"
    "// ─── handleAdminToggleSlotV2 ─────────────────────────────────────\n"
    "// Toggles a slot between 'available' and 'locked'.\n"
    "// Input: { token, slotId }\n"
    "function handleAdminToggleSlotV2(body) {\n"
    "  if (!validateAdmin(body.token)) return { success: false, error: 'unauthorized' };\n"
    "\n"
    "  var id = parseInt(body.slotId, 10);\n"
    "  if (!id) return { success: false, error: 'missing_params' };\n"
    "\n"
    "  var rows = SupabaseService.select('slots', 'id=eq.' + id + '&select=id,status');\n"
    "  if (!rows || !rows.length) return { success: false, error: 'slot_not_found' };\n"
    "  var status = rows[0].status;\n"
    "\n"
    "  var newStatus;\n"
    "  if      (status === 'available') newStatus = 'locked';\n"
    "  else if (status === 'locked')    newStatus = 'available';\n"
    "  else return { success: false, error: 'cannot_toggle', status: status };\n"
    "\n"
    "  SupabaseService.update('slots', 'id=eq.' + id, {\n"
    "    status:       newStatus,\n"
    "    last_updated: new Date().toISOString(),\n"
    "  });\n"
    "\n"
    "  return { success: true, slotId: id, prevStatus: status, newStatus: newStatus };\n"
    "}\n"
    "\n"
    "// ─── handleAdminGetClientsV2 ─────────────────────────────────────\n"
    "// Returns up to 50 clients, optionally filtered by name/phone (ilike).\n"
    "// Input: { token, search:'' }\n"
    "function handleAdminGetClientsV2(body) {\n"
    "  if (!validateAdmin(body.token)) return { success: false, error: 'unauthorized' };\n"
    "\n"
    "  var search = String(body.search || '').trim();\n"
    "  var q;\n"
    "  if (search.length >= 2) {\n"
    "    var enc = encodeURIComponent(search);\n"
    "    q = 'or=(full_name.ilike.*' + enc + '*,phone.ilike.*' + enc + '*)' +\n"
    "        '&order=created_at.desc&limit=50&select=id,phone,full_name,created_at';\n"
    "  } else {\n"
    "    q = 'order=created_at.desc&limit=50&select=id,phone,full_name,created_at';\n"
    "  }\n"
    "\n"
    "  var rows = SupabaseService.select('clients', q);\n"
    "  if (!rows) return { success: false, error: 'supabase_unavailable' };\n"
    "\n"
    "  return { success: true, clients: rows };\n"
    "}\n"
    "\n"
    "// ─── handleAdminGetClientHistoryV2 ──────────────────────────────\n"
    "// Returns a client profile + all appointments with slot times.\n"
    "// Slot data is batch-fetched in ONE query to avoid N+1 HTTP calls.\n"
    "// admin_token included per appointment for approve/reject via adminAction.\n"
    "// Input: { token, clientPhone }\n"
    "function handleAdminGetClientHistoryV2(body) {\n"
    "  if (!validateAdmin(body.token)) return { success: false, error: 'unauthorized' };\n"
    "\n"
    "  var phone = normalizePhone(String(body.clientPhone || '').trim());\n"
    "  if (!phone) return { success: false, error: 'invalid_phone' };\n"
    "\n"
    "  var clientRows = SupabaseService.select('clients',\n"
    "    'phone=eq.' + encodeURIComponent(phone) +\n"
    "    '&select=id,phone,full_name,created_at');\n"
    "  if (!clientRows || !clientRows.length) return { success: false, error: 'client_not_found' };\n"
    "  var client = clientRows[0];\n"
    "\n"
    "  var appts = SupabaseService.select('appointments',\n"
    "    'client_id=eq.' + client.id +\n"
    "    '&select=id,treatment_name,status,admin_token,calendar_event_id,created_at,slot_id,duration_min' +\n"
    "    '&order=created_at.desc');\n"
    "  if (!appts) appts = [];\n"
    "\n"
    "  // Batch-fetch all slot start_times in ONE query (no N+1)\n"
    "  var slotsMap = {};\n"
    "  var slotIds  = appts\n"
    "    .map(function (a) { return a.slot_id; })\n"
    "    .filter(function (id) { return !!id; });\n"
    "\n"
    "  if (slotIds.length > 0) {\n"
    "    var slotRows = SupabaseService.select('slots',\n"
    "      'id=in.(' + slotIds.join(',') + ')&select=id,start_time');\n"
    "    if (slotRows) {\n"
    "      slotRows.forEach(function (s) { slotsMap[s.id] = s; });\n"
    "    }\n"
    "  }\n"
    "\n"
    "  var TZ = 'Asia/Jerusalem';\n"
    "  var appointments = appts.map(function (a) {\n"
    "    var slot = slotsMap[a.slot_id];\n"
    "    var dt   = slot ? new Date(slot.start_time) : null;\n"
    "    return {\n"
    "      id:                a.id,\n"
    "      treatment_name:    a.treatment_name,\n"
    "      status:            a.status,\n"
    "      admin_token:       a.admin_token,\n"
    "      calendar_event_id: a.calendar_event_id || null,\n"
    "      created_at:        a.created_at,\n"
    "      date: dt ? Utilities.formatDate(dt, TZ, 'yyyy-MM-dd') : null,\n"
    "      time: dt ? Utilities.formatDate(dt, TZ, 'HH:mm')      : null,\n"
    "    };\n"
    "  });\n"
    "\n"
    "  return {\n"
    "    success: true,\n"
    "    client: {\n"
    "      phone:      client.phone,\n"
    "      full_name:  client.full_name,\n"
    "      created_at: client.created_at,\n"
    "    },\n"
    "    appointments: appointments,\n"
    "  };\n"
    "}\n"
)

path = 'backend/SupabaseLayer.js'
with open(path, 'r', encoding='utf-8') as f:
    src = f.read()

with open(path, 'w', encoding='utf-8') as f:
    f.write(src + NEW_CODE)

print('OK: appended', len(NEW_CODE), 'chars to', path)
